#!/usr/bin/env python3
"""Generate src/blake3-fast.js.

The optimisations are the ones from https://parsa.wtf/blake3/ that need code generation,
which is why this script exists rather than a hand-written file:

  - all 7 rounds are emitted straight-line, with the message permutation applied to the
    *indices at generation time*, so the running code never permutes anything
  - the 16 state words and the 8 chaining words are plain local variables throughout
  - message words are read from a Uint32Array view over the input, one load per word,
    instead of four byte loads and three shifts
  - the whole block loop for a 1 KiB chunk is inside one function, so there is no call
    and no argument marshalling per 64 byte block

Generated offline and committed, not built with new Function() at load time: generating
wasm or JS at runtime is what would force `wasm-unsafe-eval`/`unsafe-eval` into the CSP,
and staying out of the CSP is one of pure JS's two advantages.
"""

import re

MSG_PERMUTATION = [2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8]

# the four (a, b, c, d) quartets of a round: columns then diagonals
QUARTETS = [
    (0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15),
    (0, 5, 10, 15), (1, 6, 11, 12), (2, 7, 8, 13), (3, 4, 9, 14),
]


def schedules():
    """The message word index each g() argument reads, for each of the 7 rounds."""
    sched = list(range(16))
    out = []
    for _ in range(7):
        out.append(list(sched))
        sched = [sched[i] for i in MSG_PERMUTATION]
    return out


def g(a, b, c, d, x, y, indent):
    """One g(), as straight-line code over locals. x and y are message word names."""
    p = " " * indent
    return "\n".join([
        f"{p}v{a} = (v{a} + v{b} + {x}) | 0;",
        f"{p}v{d} ^= v{a}; v{d} = (v{d} >>> 16) | (v{d} << 16);",
        f"{p}v{c} = (v{c} + v{d}) | 0;",
        f"{p}v{b} ^= v{c}; v{b} = (v{b} >>> 12) | (v{b} << 20);",
        f"{p}v{a} = (v{a} + v{b} + {y}) | 0;",
        f"{p}v{d} ^= v{a}; v{d} = (v{d} >>> 8) | (v{d} << 24);",
        f"{p}v{c} = (v{c} + v{d}) | 0;",
        f"{p}v{b} ^= v{c}; v{b} = (v{b} >>> 7) | (v{b} << 25);",
    ])


def rounds(indent, msg=lambda i: f"m{i}"):
    """All 7 rounds, unrolled, with the permutation resolved at generation time."""
    parts = []
    for r, sched in enumerate(schedules()):
        parts.append(" " * indent + f"// round {r + 1}")
        for q, (a, b, c, d) in enumerate(QUARTETS):
            parts.append(g(a, b, c, d, msg(sched[2 * q]), msg(sched[2 * q + 1]), indent))
    return "\n".join(parts)


HEADER = '''// GENERATED by tools/gen-fast.py - do not edit. Run the script to regenerate.
//
// The optimised pure JS candidate for phase 0: BLAKE3 subtree chaining values with the
// rounds unrolled straight-line, the message permutation resolved at generation time,
// state in locals, and message words read through a Uint32Array view.
//
// Only the shape uploads need is fast here: whole 1 KiB chunks, a power-of-two count of
// them, aligned. Anything else belongs to blake3.js, which is the readable reference.

const IV0 = 0x6a09e667, IV1 = 0xbb67ae85, IV2 = 0x3c6ef372, IV3 = 0xa54ff53a;
const IV4 = 0x510e527f, IV5 = 0x9b05688c, IV6 = 0x1f83d9ab, IV7 = 0x5be0cd19;

const CHUNK_START = 1, CHUNK_END = 2, PARENT = 4, ROOT = 8;
export const CHUNK_LEN = 1024;
const WORDS_PER_CHUNK = 256;   // 1024 bytes
const WORDS_PER_BLOCK = 16;    // 64 bytes

/** Is this machine little endian? Every target we care about is; the fast path needs it. */
export const LITTLE_ENDIAN = (() => {
    const probe = new Uint32Array([1]);
    return new Uint8Array(probe.buffer)[0] === 1;
})();
'''


def chunk_function():
    """The hot loop: one 1 KiB chunk, 16 blocks, no calls inside."""
    body = ['''
/**
 * The chaining values of `chunks` consecutive whole chunks, written into `out` as 8
 * words each. `words` is a Uint32Array view of the input, starting at `wordOff`.
 *
 * The 16 blocks of a chunk are handled in one function so that nothing is passed, and
 * the chaining value stays in locals from the chunk's first block to its last.
 */
export function chunkCVs(words, wordOff, chunks, counterStart, out) {
    let outAt = 0;
    for (let chunk = 0; chunk < chunks; chunk++) {
        const counterLow = (counterStart + chunk) >>> 0;
        const counterHigh = Math.floor((counterStart + chunk) / 4294967296) >>> 0;
        let h0 = IV0, h1 = IV1, h2 = IV2, h3 = IV3, h4 = IV4, h5 = IV5, h6 = IV6, h7 = IV7;
        const base = wordOff + chunk * WORDS_PER_CHUNK;
        // CHUNK_START belongs to block 0 and CHUNK_END to block 15, so the 16 iterations
        // are run with a flags value that is constant per iteration rather than tested
        for (let block = 0; block < 16; block++) {
            const flags = block === 0 ? CHUNK_START : block === 15 ? CHUNK_END : 0;
            const o = base + block * WORDS_PER_BLOCK;
            const m0 = words[o], m1 = words[o + 1], m2 = words[o + 2], m3 = words[o + 3];
            const m4 = words[o + 4], m5 = words[o + 5], m6 = words[o + 6], m7 = words[o + 7];
            const m8 = words[o + 8], m9 = words[o + 9], m10 = words[o + 10], m11 = words[o + 11];
            const m12 = words[o + 12], m13 = words[o + 13], m14 = words[o + 14], m15 = words[o + 15];
            let v0 = h0, v1 = h1, v2 = h2, v3 = h3, v4 = h4, v5 = h5, v6 = h6, v7 = h7;
            let v8 = IV0, v9 = IV1, v10 = IV2, v11 = IV3;
            let v12 = counterLow, v13 = counterHigh, v14 = 64, v15 = flags;
''']
    body.append(rounds(12))
    body.append('''
            h0 = v0 ^ v8; h1 = v1 ^ v9; h2 = v2 ^ v10; h3 = v3 ^ v11;
            h4 = v4 ^ v12; h5 = v5 ^ v13; h6 = v6 ^ v14; h7 = v7 ^ v15;
        }
        out[outAt] = h0; out[outAt + 1] = h1; out[outAt + 2] = h2; out[outAt + 3] = h3;
        out[outAt + 4] = h4; out[outAt + 5] = h5; out[outAt + 6] = h6; out[outAt + 7] = h7;
        outAt += 8;
    }
}
''')
    return "".join(body)


def parent_function():
    """Parent compressions: 1 per 2 chunks, so readability over speed here."""
    body = ['''
/**
 * A parent node: compress two chaining values into one. `left`/`right` are word offsets
 * into `cvs`; the result is written at `outAt` in `out`. `root` finalises instead.
 */
export function parentCV(cvs, left, right, out, outAt, root) {
    const m0 = cvs[left], m1 = cvs[left + 1], m2 = cvs[left + 2], m3 = cvs[left + 3];
    const m4 = cvs[left + 4], m5 = cvs[left + 5], m6 = cvs[left + 6], m7 = cvs[left + 7];
    const m8 = cvs[right], m9 = cvs[right + 1], m10 = cvs[right + 2], m11 = cvs[right + 3];
    const m12 = cvs[right + 4], m13 = cvs[right + 5], m14 = cvs[right + 6], m15 = cvs[right + 7];
    let v0 = IV0, v1 = IV1, v2 = IV2, v3 = IV3, v4 = IV4, v5 = IV5, v6 = IV6, v7 = IV7;
    let v8 = IV0, v9 = IV1, v10 = IV2, v11 = IV3;
    let v12 = 0, v13 = 0, v14 = 64, v15 = PARENT | (root ? ROOT : 0);
''']
    body.append(rounds(4))
    body.append('''
    out[outAt] = v0 ^ v8; out[outAt + 1] = v1 ^ v9;
    out[outAt + 2] = v2 ^ v10; out[outAt + 3] = v3 ^ v11;
    out[outAt + 4] = v4 ^ v12; out[outAt + 5] = v5 ^ v13;
    out[outAt + 6] = v6 ^ v14; out[outAt + 7] = v7 ^ v15;
}
''')
    return "".join(body)


API = '''
// Scratch reused across calls: a 4 MiB chunk is 4096 chunk CVs of 8 words.
//
// Int32Array rather than Uint32Array throughout: a Uint32Array load of a word with the
// top bit set is a value above 2^31, which JS can only represent as a double, so every
// such load boxes and every store unboxes. Int32 arithmetic with |0 gives bit-identical
// results and stays in tagged integers. This is worth ~3x in Firefox.
let cvScratch = new Int32Array(4096 * 8);
const resultWords = new Int32Array(8);

/**
 * The chaining value of one aligned, power-of-two subtree: the call an upload makes per
 * 4 MiB chunk. Returns 32 bytes.
 *
 * `bytes` must be 4 byte aligned within its buffer, which File.slice() ArrayBuffers are.
 */
export function subtreeCV(bytes, chunkIndex) {
    return subtreeWith(chunkCVs, bytes, chunkIndex);
}

function subtreeWith(hashChunks, bytes, chunkIndex) {
    const chunks = bytes.length / CHUNK_LEN;
    if (! Number.isInteger(chunks) || chunks < 1 || (chunks & (chunks - 1)) !== 0)
        throw new Error("fast path wants a power of two whole chunks, got " + bytes.length + " bytes");
    if (chunkIndex % chunks !== 0)
        throw new Error("subtree of " + chunks + " chunks must start at a multiple of " + chunks);
    if (! LITTLE_ENDIAN)
        throw new Error("fast path assumes a little endian machine");
    if ((bytes.byteOffset & 3) !== 0)
        throw new Error("fast path wants a 4 byte aligned view");

    const words = new Int32Array(bytes.buffer, bytes.byteOffset, bytes.length >>> 2);
    if (cvScratch.length < chunks * 8)
        cvScratch = new Int32Array(chunks * 8);
    hashChunks(words, 0, chunks, chunkIndex, cvScratch);

    // merge in place, level by level, the last merge being a parent (not root: this is a
    // subtree of a bigger file)
    let count = chunks;
    while (count > 1) {
        for (let i = 0; i < count / 2; i++)
            parentCV(cvScratch, i * 16, i * 16 + 8, cvScratch, i * 8, false);
        count /= 2;
    }
    return wordsToBytes(cvScratch, 8);
}

/** Merge two subtree CVs (32 bytes each). */
export function mergeNonRoot(leftCV, rightCV) {
    return merge(leftCV, rightCV, false);
}

/** Merge the top two CVs into the hash of the whole file. */
export function mergeRoot(leftCV, rightCV) {
    return merge(leftCV, rightCV, true);
}

const mergeScratch = new Int32Array(16);

function merge(leftCV, rightCV, root) {
    bytesToWords(leftCV, mergeScratch, 0);
    bytesToWords(rightCV, mergeScratch, 8);
    parentCV(mergeScratch, 0, 8, resultWords, 0, root);
    return wordsToBytes(resultWords, 8);
}

function bytesToWords(bytes, into, at) {
    for (let i = 0; i < 8; i++) {
        const o = i * 4;
        into[at + i] = bytes[o] | (bytes[o + 1] << 8) | (bytes[o + 2] << 16) | (bytes[o + 3] << 24);
    }
}

function wordsToBytes(words, count) {
    const out = new Uint8Array(count * 4);
    for (let i = 0; i < count; i++) {
        const w = words[i];
        out[i * 4] = w & 0xff;
        out[i * 4 + 1] = (w >>> 8) & 0xff;
        out[i * 4 + 2] = (w >>> 16) & 0xff;
        out[i * 4 + 3] = (w >>> 24) & 0xff;
    }
    return out;
}
'''


SMALL = """
// A second shape of the same unrolled code, for comparison: the 7 rounds live in their
// own per-block function rather than inside the chunk loop. Firefox was 3.4x slower than
// Chromium on the big version, which looks like a limit on how large a function the
// engine will fully optimise; this measures that rather than guessing.
const blockOut = new Int32Array(8);

function compressBlock(h0, h1, h2, h3, h4, h5, h6, h7,
                       m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15,
                       counterLow, counterHigh, flags) {
    let v0 = h0, v1 = h1, v2 = h2, v3 = h3, v4 = h4, v5 = h5, v6 = h6, v7 = h7;
    let v8 = IV0, v9 = IV1, v10 = IV2, v11 = IV3;
    let v12 = counterLow, v13 = counterHigh, v14 = 64, v15 = flags;
%s
    blockOut[0] = v0 ^ v8; blockOut[1] = v1 ^ v9; blockOut[2] = v2 ^ v10; blockOut[3] = v3 ^ v11;
    blockOut[4] = v4 ^ v12; blockOut[5] = v5 ^ v13; blockOut[6] = v6 ^ v14; blockOut[7] = v7 ^ v15;
}

/** Same result as chunkCVs, with the rounds behind a call. */
export function chunkCVsSmall(words, wordOff, chunks, counterStart, out) {
    let outAt = 0;
    for (let chunk = 0; chunk < chunks; chunk++) {
        const counterLow = (counterStart + chunk) >>> 0;
        const counterHigh = Math.floor((counterStart + chunk) / 4294967296) >>> 0;
        let h0 = IV0, h1 = IV1, h2 = IV2, h3 = IV3, h4 = IV4, h5 = IV5, h6 = IV6, h7 = IV7;
        const base = wordOff + chunk * WORDS_PER_CHUNK;
        for (let block = 0; block < 16; block++) {
            const o = base + block * WORDS_PER_BLOCK;
            compressBlock(h0, h1, h2, h3, h4, h5, h6, h7,
                words[o], words[o + 1], words[o + 2], words[o + 3],
                words[o + 4], words[o + 5], words[o + 6], words[o + 7],
                words[o + 8], words[o + 9], words[o + 10], words[o + 11],
                words[o + 12], words[o + 13], words[o + 14], words[o + 15],
                counterLow, counterHigh,
                (block === 0 ? CHUNK_START : 0) | (block === 15 ? CHUNK_END : 0));
            h0 = blockOut[0]; h1 = blockOut[1]; h2 = blockOut[2]; h3 = blockOut[3];
            h4 = blockOut[4]; h5 = blockOut[5]; h6 = blockOut[6]; h7 = blockOut[7];
        }
        out[outAt] = h0; out[outAt + 1] = h1; out[outAt + 2] = h2; out[outAt + 3] = h3;
        out[outAt + 4] = h4; out[outAt + 5] = h5; out[outAt + 6] = h6; out[outAt + 7] = h7;
        outAt += 8;
    }
}

/** subtreeCV using the small-function shape, for the same comparison. */
export function subtreeCVSmall(bytes, chunkIndex) {
    return subtreeWith(chunkCVsSmall, bytes, chunkIndex);
}
"""


def permutation_swaps(indent):
    """In-place message permutation, as two variable cycles. Derived from
    MSG_PERMUTATION rather than copied: new[i] = old[MSG_PERMUTATION[i]]."""
    seen, cycles = set(), []
    for start in range(16):
        if start in seen:
            continue
        cyc, seen_next = [start], MSG_PERMUTATION[start]
        seen.add(start)
        while seen_next != start:
            cyc.append(seen_next)
            seen.add(seen_next)
            seen_next = MSG_PERMUTATION[seen_next]
        if len(cyc) > 1:
            cycles.append(cyc)
    p = " " * indent
    lines = []
    for n, cyc in enumerate(cycles):
        lines.append(f"{p}const t{n} = m{cyc[0]};")
        for a, b in zip(cyc, cyc[1:]):
            lines.append(f"{p}m{a} = m{b};")
        lines.append(f"{p}m{cyc[-1]} = t{n};")
    return "\n".join(lines)


LOOP7 = """
// A third shape: one round body inside a loop of 7, with the permutation applied by
// swapping the message variables - the shape the write-up ends on. About a seventh of the
// code of chunkCVs, which matters if an engine will not fully optimise a huge function.
export function chunkCVsLoop(words, wordOff, chunks, counterStart, out) {
    let outAt = 0;
    for (let chunk = 0; chunk < chunks; chunk++) {
        const counterLow = (counterStart + chunk) >>> 0;
        const counterHigh = Math.floor((counterStart + chunk) / 4294967296) >>> 0;
        let h0 = IV0, h1 = IV1, h2 = IV2, h3 = IV3, h4 = IV4, h5 = IV5, h6 = IV6, h7 = IV7;
        const base = wordOff + chunk * WORDS_PER_CHUNK;
        for (let block = 0; block < 16; block++) {
            const flags = block === 0 ? CHUNK_START : block === 15 ? CHUNK_END : 0;
            const o = base + block * WORDS_PER_BLOCK;
            let m0 = words[o], m1 = words[o + 1], m2 = words[o + 2], m3 = words[o + 3];
            let m4 = words[o + 4], m5 = words[o + 5], m6 = words[o + 6], m7 = words[o + 7];
            let m8 = words[o + 8], m9 = words[o + 9], m10 = words[o + 10], m11 = words[o + 11];
            let m12 = words[o + 12], m13 = words[o + 13], m14 = words[o + 14], m15 = words[o + 15];
            let v0 = h0, v1 = h1, v2 = h2, v3 = h3, v4 = h4, v5 = h5, v6 = h6, v7 = h7;
            let v8 = IV0, v9 = IV1, v10 = IV2, v11 = IV3;
            let v12 = counterLow, v13 = counterHigh, v14 = 64, v15 = flags;
            for (let r = 0; r < 7; r++) {
%s
                if (r !== 6) {
%s
                }
            }
            h0 = v0 ^ v8; h1 = v1 ^ v9; h2 = v2 ^ v10; h3 = v3 ^ v11;
            h4 = v4 ^ v12; h5 = v5 ^ v13; h6 = v6 ^ v14; h7 = v7 ^ v15;
        }
        out[outAt] = h0; out[outAt + 1] = h1; out[outAt + 2] = h2; out[outAt + 3] = h3;
        out[outAt + 4] = h4; out[outAt + 5] = h5; out[outAt + 6] = h6; out[outAt + 7] = h7;
        outAt += 8;
    }
}

/** subtreeCV using the looped shape, for the same comparison. */
export function subtreeCVLoop(bytes, chunkIndex) {
    return subtreeWith(chunkCVsLoop, bytes, chunkIndex);
}
"""


MEM = """
// A fourth shape: the message words are not held in locals at all, but read from the
// typed array at each use. The permutation is resolved at generation time, so every index
// is a constant. This trades 16 live locals for 7 loads per word - worth measuring where
// register pressure, not load count, is the limit.
export function chunkCVsMem(words, wordOff, chunks, counterStart, out) {
    let outAt = 0;
    for (let chunk = 0; chunk < chunks; chunk++) {
        const counterLow = (counterStart + chunk) >>> 0;
        const counterHigh = Math.floor((counterStart + chunk) / 4294967296) >>> 0;
        let h0 = IV0, h1 = IV1, h2 = IV2, h3 = IV3, h4 = IV4, h5 = IV5, h6 = IV6, h7 = IV7;
        const base = wordOff + chunk * WORDS_PER_CHUNK;
        for (let block = 0; block < 16; block++) {
            const flags = block === 0 ? CHUNK_START : block === 15 ? CHUNK_END : 0;
            const o = base + block * WORDS_PER_BLOCK;
            let v0 = h0, v1 = h1, v2 = h2, v3 = h3, v4 = h4, v5 = h5, v6 = h6, v7 = h7;
            let v8 = IV0, v9 = IV1, v10 = IV2, v11 = IV3;
            let v12 = counterLow, v13 = counterHigh, v14 = 64, v15 = flags;
%s
            h0 = v0 ^ v8; h1 = v1 ^ v9; h2 = v2 ^ v10; h3 = v3 ^ v11;
            h4 = v4 ^ v12; h5 = v5 ^ v13; h6 = v6 ^ v14; h7 = v7 ^ v15;
        }
        out[outAt] = h0; out[outAt + 1] = h1; out[outAt + 2] = h2; out[outAt + 3] = h3;
        out[outAt + 4] = h4; out[outAt + 5] = h5; out[outAt + 6] = h6; out[outAt + 7] = h7;
        outAt += 8;
    }
}

/** subtreeCV reading message words from memory, for the same comparison. */
export function subtreeCVMem(bytes, chunkIndex) {
    return subtreeWith(chunkCVsMem, bytes, chunkIndex);
}
"""


def interleaved_rounds(indent):
    """Two independent chunks' rounds, interleaved statement by statement.

    Each block depends on the one before it, so a single chunk is a long dependency
    chain and the processor stalls on it. Two chunks are independent, so interleaving
    them gives it something to do in the gaps. This is the scalar form of what the
    wasm SIMD build does with lanes."""
    lanes = []
    for lane in ("a", "b"):
        text = rounds(indent, msg=lambda i, lane=lane: f"{lane}m{i}")
        # rename the state variables per lane. A word boundary regex, not str.replace:
        # replacing "v1" textually also hits the "v1" inside an already renamed "av12".
        text = re.sub(r"\bv(\d+)\b", lane + r"v\1", text)
        lanes.append([l for l in text.split("\n") if l.strip() and "// round" not in l])
    assert len(lanes[0]) == len(lanes[1])
    out = []
    for x, y in zip(*lanes):
        out.append(x)
        out.append(y)
    return "\n".join(out)


X2 = """
// A fifth shape: two chunks hashed at once, their rounds interleaved.
export function chunkCVsX2(words, wordOff, chunks, counterStart, out) {
    let outAt = 0;
    for (let chunk = 0; chunk + 1 < chunks; chunk += 2) {
        const aCounterLow = (counterStart + chunk) >>> 0;
        const bCounterLow = (counterStart + chunk + 1) >>> 0;
        const counterHigh = Math.floor((counterStart + chunk) / 4294967296) >>> 0;
        let ah0 = IV0, ah1 = IV1, ah2 = IV2, ah3 = IV3, ah4 = IV4, ah5 = IV5, ah6 = IV6, ah7 = IV7;
        let bh0 = IV0, bh1 = IV1, bh2 = IV2, bh3 = IV3, bh4 = IV4, bh5 = IV5, bh6 = IV6, bh7 = IV7;
        const aBase = wordOff + chunk * WORDS_PER_CHUNK;
        const bBase = aBase + WORDS_PER_CHUNK;
        for (let block = 0; block < 16; block++) {
            const flags = block === 0 ? CHUNK_START : block === 15 ? CHUNK_END : 0;
            const ao = aBase + block * WORDS_PER_BLOCK;
            const bo = bBase + block * WORDS_PER_BLOCK;
            const am0 = words[ao], am1 = words[ao + 1], am2 = words[ao + 2], am3 = words[ao + 3];
            const am4 = words[ao + 4], am5 = words[ao + 5], am6 = words[ao + 6], am7 = words[ao + 7];
            const am8 = words[ao + 8], am9 = words[ao + 9], am10 = words[ao + 10], am11 = words[ao + 11];
            const am12 = words[ao + 12], am13 = words[ao + 13], am14 = words[ao + 14], am15 = words[ao + 15];
            const bm0 = words[bo], bm1 = words[bo + 1], bm2 = words[bo + 2], bm3 = words[bo + 3];
            const bm4 = words[bo + 4], bm5 = words[bo + 5], bm6 = words[bo + 6], bm7 = words[bo + 7];
            const bm8 = words[bo + 8], bm9 = words[bo + 9], bm10 = words[bo + 10], bm11 = words[bo + 11];
            const bm12 = words[bo + 12], bm13 = words[bo + 13], bm14 = words[bo + 14], bm15 = words[bo + 15];
            let av0 = ah0, av1 = ah1, av2 = ah2, av3 = ah3, av4 = ah4, av5 = ah5, av6 = ah6, av7 = ah7;
            let av8 = IV0, av9 = IV1, av10 = IV2, av11 = IV3;
            let av12 = aCounterLow, av13 = counterHigh, av14 = 64, av15 = flags;
            let bv0 = bh0, bv1 = bh1, bv2 = bh2, bv3 = bh3, bv4 = bh4, bv5 = bh5, bv6 = bh6, bv7 = bh7;
            let bv8 = IV0, bv9 = IV1, bv10 = IV2, bv11 = IV3;
            let bv12 = bCounterLow, bv13 = counterHigh, bv14 = 64, bv15 = flags;
%s
            ah0 = av0 ^ av8; ah1 = av1 ^ av9; ah2 = av2 ^ av10; ah3 = av3 ^ av11;
            ah4 = av4 ^ av12; ah5 = av5 ^ av13; ah6 = av6 ^ av14; ah7 = av7 ^ av15;
            bh0 = bv0 ^ bv8; bh1 = bv1 ^ bv9; bh2 = bv2 ^ bv10; bh3 = bv3 ^ bv11;
            bh4 = bv4 ^ bv12; bh5 = bv5 ^ bv13; bh6 = bv6 ^ bv14; bh7 = bv7 ^ bv15;
        }
        out[outAt] = ah0; out[outAt + 1] = ah1; out[outAt + 2] = ah2; out[outAt + 3] = ah3;
        out[outAt + 4] = ah4; out[outAt + 5] = ah5; out[outAt + 6] = ah6; out[outAt + 7] = ah7;
        out[outAt + 8] = bh0; out[outAt + 9] = bh1; out[outAt + 10] = bh2; out[outAt + 11] = bh3;
        out[outAt + 12] = bh4; out[outAt + 13] = bh5; out[outAt + 14] = bh6; out[outAt + 15] = bh7;
        outAt += 16;
    }
    // an odd chunk at the end, if any
    if (chunks & 1)
        chunkCVs(words, wordOff + (chunks - 1) * WORDS_PER_CHUNK, 1, counterStart + chunks - 1,
            out.subarray(outAt));
}

/** subtreeCV hashing two chunks at a time. */
export function subtreeCVX2(bytes, chunkIndex) {
    return subtreeWith(chunkCVsX2, bytes, chunkIndex);
}
"""


def main():
    import os
    one_round = "\n".join(
        g(a, b, c, d, f"m{2 * q}", f"m{2 * q + 1}", 16)
        for q, (a, b, c, d) in enumerate(QUARTETS))
    out = (HEADER + chunk_function() + parent_function() + API + (SMALL % rounds(4))
           + (LOOP7 % (one_round, permutation_swaps(20)))
           + (MEM % rounds(12, msg=lambda i: f"words[o + {i}]"))
           + (X2 % interleaved_rounds(12)))
    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "src", "blake3-fast.js")
    with open(path, "w") as f:
        f.write(out)
    print("wrote %s (%d lines)" % (path, out.count("\n") + 1))


if __name__ == "__main__":
    main()
